// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXEZwtGz9rjYyZv6dKZ9iOL2VEMhAkMd0',
    appId: '1:63089949281:web:e5668577b26ab0bad6c820',
    messagingSenderId: '63089949281',
    projectId: 'solar-consult',
    authDomain: 'solar-consult.firebaseapp.com',
    databaseURL: 'https://solar-consult-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'solar-consult.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPs9ANXiZ9RdBZgWMHxttZc4Me5so-brg',
    appId: '1:63089949281:android:5f96ba0dfafa7c6cd6c820',
    messagingSenderId: '63089949281',
    projectId: 'solar-consult',
    databaseURL: 'https://solar-consult-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'solar-consult.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv89bcvL8qaeUhGOISwTN7Nl-mfNCSQfk',
    appId: '1:63089949281:ios:db389b610fc77fccd6c820',
    messagingSenderId: '63089949281',
    projectId: 'solar-consult',
    databaseURL: 'https://solar-consult-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'solar-consult.appspot.com',
    iosClientId: '63089949281-1e5e93ql26d18b1c9grl7lektmssrit8.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );
}
